---
application:
  name: "nodejs-posgresql"
  project: "abrteam-api"
  organization: "QoveryCommunity"
routers:
- name: "main-nodejs-posgresql"
  routes:
  - application_name: "nodejs-posgresql"
    paths:
    - "/*"
